### ISSUE TITLE
Support for Command.setArgumentTransformer

### ISSUE THREAD

**Issue by haakonnessjoen** [stipsan/ioredis-mock#1051]
We are using this handy piece of code, to be able to work with hashes as objects in js:

```javascript
function convertMapToArray(map: any): any[] {
	const result: any[] = []
	let pos = 0
	map.forEach(function (value: any, key: any) {
		result[pos] = key
		result[pos + 1] = value
		pos += 2
	})
	return result
}

function convertObjectToArray(obj: any): any[] {
	var result: any[] = []
	var keys = Object.keys(obj)

	for (var i = 0, l = keys.length; i < l; i++) {
		result.push(keys[i], obj[keys[i]])
	}
	return result
}

Redis.Command.setArgumentTransformer('hmset', function (args) {
	if (args.length === 2) {
		if (typeof Map !== 'undefined' && args[1] instanceof Map) {
			// utils is a internal module of ioredis
			return [args[0]].concat(convertMapToArray(args[1]))
		}
		if (typeof args[1] === 'object' && args[1] !== null) {
			return [args[0]].concat(convertObjectToArray(args[1]))
		}
	}
	return args
})

Redis.Command.setReplyTransformer('hgetall', function (result) {
	if (Array.isArray(result)) {
		const obj: any = {}
		for (var i = 0; i < result.length; i += 2) {
			obj[result[i]] = result[i + 1]
		}
		return obj
	}
	return result
})
```

But when using ioredis-mock, i get the following error:
```
TypeError: Cannot read property 'setArgumentTransformer' of undefined

      23 | }
      24 |
    > 25 | Redis.Command.setArgumentTransformer('hmset', function (args) {
         |               ^
      26 |      if (args.length === 2) {
      27 |              if (typeof Map !== 'undefined' && args[1] instanceof Map) {
      28 |                      // utils is a internal module of ioredis

      at Object.<anonymous> (src/lib/redis.ts:25:15)
```

So I guess that is not supported, as it works without ioredis-mock. It would be awesome to get support for that though.

**Comment by haakonnessjoen** [comment]
Ok. So I see now that you are supposed to support it.
So the way I am using it now is with jest and this code:

```
const ioredisMock = require('ioredis-mock')
jest.setMock('ioredis', ioredisMock)
```

In the other module using ioredis, I tried `console.log("Redis:", Redis)` and `console.log("Redis.Command:", Redis.Command)`, and got the following when it is being mocked:
```
Redis: [class RedisMock extends EventEmitter]
Redis.Command: undefined
```

And I am using ioredis-mock@5.2.4

**Comment by stipsan** [comment]
Yeah the thing is that it's tricky to make jest module mocking work when the mock is [importing](https://github.com/stipsan/ioredis-mock/blob/3683c0ae02539d8b3080c9cd54902b22a221e4a4/src/index.js#L2) [something](https://github.com/stipsan/ioredis-mock/blob/3683c0ae02539d8b3080c9cd54902b22a221e4a4/src/index.js#L141-L151) from the original.

There's more alternative approaches in this thread: https://github.com/stipsan/ioredis-mock/issues/568

It sounds like this approach is the most likely to succeed, but perhaps cost the most to implement, depending on how many import calls in your codebase that'll need to be updated: https://github.com/stipsan/ioredis-mock/issues/568#issuecomment-427612326

Perhaps the best solution here is if we added another import you could use, specifically for jest:
```
const ioredisMock = require('ioredis-mock/jest')
jest.setMock('ioredis', ioredisMock)
```

In the `ioredis-mock/jest.js` file we could simply inline `import { Command } from 'ioredis';` to ensure that the jest module mocking system no longer have to deal with the circular dependency.

**Comment by stipsan** [comment]
@haakonnessjoen starting with `v5.4` you can use this approach:
```js
jest.mock('ioredis', () => require('ioredis-mock/jest'));
```

**Comment by haakonnessjoen** [comment]
I am still having the same issue:
`TypeError: Cannot read property 'setArgumentTransformer' of undefined`

Is it simply that ioredis-mock do not work with typescript at all, since ioredis is imported in the main code?

**Comment by stipsan** [comment]
> I am still having the same issue:
> 
> `TypeError: Cannot read property 'setArgumentTransformer' of undefined`
> 
> 
> 
> Is it simply that ioredis-mock do not work with typescript at all, since ioredis is imported in the main code?
> 
> 
> 
> 
Is that with the new `ioredis-mock/jest` approach? I'll go over the test suite, it should be testing this already 🤔

**Comment by silverwind** [comment]
Yes, I see it with `ioredis-mock/jest`. My `setupFiles` has:

```js
jest.mock("ioredis", () => require("ioredis-mock/jest"));
```

My application uses:

```js
Redis.Command.setReplyTransformer("hgetall", result => {
  const arr = [];
  for (let i = 0; i < result.length; i += 2) {
    arr.push([String(result[i]), String(result[i + 1])]);
  }
  return arr;
});
```

During the jest run, It throws:

```
TypeError: Cannot read properties of undefined (reading 'setReplyTransformer')
```

**Comment by silverwind** [comment]
I think the issue is that these transformer functions are implemented as `RedisMock.prototype.Command`, e.g. the prototype, but they should not be on the prototype, but on `RedisMock.Command` itself as per [docs](https://github.com/luin/ioredis#transforming-arguments--replies).
