### ISSUE TITLE
[new command]: LINSERT not implemented yet

### ISSUE THREAD

**Issue by onichandame** [stipsan/ioredis-mock#1052]
### Problem

the [LINSERT](https://redis.io/commands/linsert) is already available in ioredis. But it is undefined in ioredis-mock. After quick searches in the issues, it has not even been raised as an issue. I guess there might be some rationales behind it or simply nobody needed to use this command. Any information about it?

**Comment by stipsan** [comment]
Yeah it's simply not been requested by anyone yet 🙂 You can see a full list of supported commands here: https://github.com/stipsan/ioredis-mock/blob/master/compat.md
The goal is to eventually get 100% coverage 😉

**Comment by onichandame** [comment]
closed by #1053
