### ISSUE TITLE
mock psubscribe should emit 'pmessage' events, not 'message' events

### ISSUE THREAD

**Issue by jedwards1211** [stipsan/ioredis-mock#1072]
`ioredis` emits `'pmessage'` events for `psubscribe` subscriptions:
![image](https://user-images.githubusercontent.com/1448194/116498143-a733f080-a86e-11eb-8da2-a79a21d58374.png)

So the new `psubscribe` implementation in `ioredis-mock` is incorrect: `'pmessage'` and `"pmessage"` are nowhere to be found in the codebase.  The source code and tests use `'message'` events instead.

**Comment by jedwards1211** [comment]
`pmessage`/`pmessageBuffer` events also have a different callback signature than `message` events...whoever implemented `psubscribe`/`punsubscribe` appears to not have used the real thing much.

**Comment by stipsan** [comment]
Great to see someone who've used it a lot have enough time to contribute a PR 🎉 I'll review right away 🏎️ 💨
