### ISSUE TITLE
Build fails with Next.js 12 when using ioredis-mock

### ISSUE THREAD

**Issue by blenderskool** [stipsan/ioredis-mock#1103]
This issue might be more specific to Next.js 12, but I observed a very peculiar issue with a potential fix in this package.

When using this package with Next.js 12, the production build using `next build` is stuck indefinitely at  
`Creating an optimized production build...`. This does not happen with Next.js 11.

At first, I thought it was the new SWC compiler that had some bug but disabling it had no effect.

A little digging of files in this package brought me to the `commands/lrem.js` file. This line seems to have some issue.
https://github.com/stipsan/ioredis-mock/blob/7979c220de973f974915340e9aa13f8304ac5855/src/commands/lrem.js#L7

When changing to the following:
```js
const indexFun = count < 0 ? list.lastIndexOf : list.indexOf;
```
The command `next build` completes successfully.
I don't fully understand why this line which semantically is the same causes a hiccup in production builds.

If this issue does not belong here, please let me know, I'll open it in the next.js repository.

Edit: There's nothing special in the project, here's a [small test project](https://stackblitz.com/edit/nextjs-t5feml?file=lib%2Fredis.js) I created that produces this issue.

**Comment by enzoferey** [comment]
Any updates on this one ?

I can confirm the issue still exists on Vercel nowadays with `next@12.1.5`. The patch still works as well with `ioredis-mock@7.2.0`.

**Comment by enzoferey** [comment]
Nice ! Thanks 🚀
