### ISSUE TITLE
Calling `flushdb` "forks" shared redis backends (v6.x)

### ISSUE THREAD

**Issue by evantahler** [stipsan/ioredis-mock#1124]
In the new v.6.x line, mock redis connections that share the same connection information should share the same backend.  However, calling `flushdb` on one connection "detaches" it from the others:

```ts
const Redis = require("ioredis-mock");

const run = async () => {
  const redis1 = new Redis();
  const redis2 = new Redis();

  await redis1.set("foo", "bar");
  console.log(await redis1.get("foo")); // 👍 bar
  console.log(await redis2.get("foo")); // 👍 bar

  await redis1.flushdb();
  console.log(await redis1.get("foo")); // ❌ null
  console.log(await redis2.get("foo")); // 👍 bar

  await redis1.set("foo", "bloop");
  console.log(await redis1.get("foo")); // 👍 bloop
  console.log(await redis2.get("foo")); // ❌ bar
};

run();

```

I would expect the value of "foo" for both databases to be null after calling `flushdb`. More insidiously, form that point forward, reads and write don't effect each other.

**Comment by stipsan** [comment]
Thanks for the report! Giving it a look in a bit 🕵️

**Comment by stipsan** [comment]
Added your repro in the testing suite: https://github.com/stipsan/ioredis-mock/blob/c7a49314020dcd015de1d946ebea30a3dd782ee9/test/integration/commands/flushdb.js#L15-L30

Will merge and release in a minute

**Comment by evantahler** [comment]
Thank you!
