### ISSUE TITLE
Unexpected true value, for non-existing key

### ISSUE THREAD

**Issue by tada5hi** [stipsan/ioredis-mock#1149]
- I'not quite sure why this is happening, but the library is returning `true` for an non existing redis key ^^. This issue occurs when i try to update from version 5.9.1 to 7.0.0.
- I think the error should be caused by changes to the `src/data.js` file, but i didn't took a deep look into it yet.
- Maybe you detect it sooner ^^

**Comment by tada5hi** [comment]
https://github.com/tada5hi/redis-extension/pull/21

**Comment by stipsan** [comment]
Hi, you're most likely affected by the change explained [here](https://github.com/stipsan/ioredis-mock#from-v5-to-v6).
Unless it's a bug/regression in `redis.expire`?
