### ISSUE TITLE
ioredis v5 filename case change breaks import of built/command.ts

### ISSUE THREAD

**Issue by actraiser** [stipsan/ioredis-mock#1164]
I have upgraded ioredis to v5 and noticed that my tests work fine on Mac but not on the CI running Linux. 

```
 Cannot find module 'ioredis/built/command' from '../../node_modules/ioredis-mock/lib/index.js'
```

As it turns out, the casing for the module changed in ioredis v5 from **built/command.ts** to **built/Command.ts**. OSX is case-insensitive, so tests were still working locally but not when I ran them trough the linux-based deployment pipeline.

additional note, just saw this pull request which I believe fails for the described reason: [1163](https://github.com/stipsan/ioredis-mock/pull/1163)

Greets
-act

**Comment by ehaynes99** [comment]
Doesn't look like there is any support for ioredis 5 yet. It shouldn't even install...

https://github.com/stipsan/ioredis-mock/blob/6302c57fec7f3a3588e0f0f157789f6b47805d66/package.json#L52-L54

**Comment by actraiser** [comment]
#1163 seems to address an update of ioredis-mock to a new major version in the near future. I will disable the tests involving ioredis-mock for the time being as we upgraded to ioredis 5 already. Thanks again.

greets
-act

**Comment by crobinson42** [comment]
This has turned into a blocker
<img width="598" alt="image" src="https://user-images.githubusercontent.com/5973579/165576846-27e0de73-6950-4eeb-91c5-e2a2360acf10.png">
