### ISSUE TITLE
nodes is not a function error (redis cluster)

### ISSUE THREAD

**Issue by akhan5** [stipsan/ioredis-mock#1196]
@stipsan I tried to use the ioredis-mock library in our project with the following line of code to mock redis cluster.

`jest.mock("ioredis", () => jest.requireActual("ioredis-mock"));`

but I am getting (`nodes is not a function`) error in test cases.

Here is a reference to nodes() command in ioredis library. https://github.com/luin/ioredis#running-commands-to-multiple-nodes

**Comment by stipsan** [comment]
Hi, Clusters are indeed not fully supported. PRs welcome ☺️
