### ISSUE TITLE
Support for Redis 6

### ISSUE THREAD

**Issue by felixmosh** [stipsan/ioredis-mock#1199]
Hi, there is any plan to update the mock to support Redis 6?

**Comment by stipsan** [comment]
Support it how? There's no changes that intentionally break v6 even though end-to-end tests and more is on v7.

**Comment by felixmosh** [comment]
BullMQ throws warnings on redis version below 6...
Now the version is hardcoded into the string, maybe, we can make it dynamic?

**Comment by stipsan** [comment]
Gotcha, I wrote a script ([`npm run update-data`](https://github.com/stipsan/ioredis-mock/blob/f1b33c454b611cef331e7f81065cc531928f8f10/package.json#LL65C6-L65C6)) which snapshots the redis version from the one that is end-to-end tested on the CI, but I forgot to update the `info` command to use it 🤦 

Fixing 😄
