### ISSUE TITLE
The `publish` command is a stub

### ISSUE THREAD

**Issue by stipsan** [stipsan/ioredis-mock#156]
Right now it's a stub but due to being in the array the compat table reports it as a supported feature. 
Removing it would be a breaking change so this issue will be a reminder to implement it properly later when channels are implemented.

**Comment by Parcley** [comment]
I am interested in the publish / subscribe / unsubscribe feature and might work on a PR, which adds at least partial support for these commands.
Anything I should bear in mind when working on this?

**Comment by Parcley** [comment]
To start with, I thought of implementing the channels as EventEmitter?

**Comment by stipsan** [comment]
Hey, that's awesome! :D 

You can look at how we emit `ready` and `connect` events today to start:
https://github.com/stipsan/ioredis-mock/blob/eea071667bc915e016e53bbd09cd5b8b866f9777/src/index.js#L45

https://github.com/stipsan/ioredis-mock/blob/eea071667bc915e016e53bbd09cd5b8b866f9777/src/commands-utils/emitConnectEvent.js

Other than that, go ahead 👍

**Comment by Parcley** [comment]
have a look at PR #655

**Comment by Parcley** [comment]
should be resolved now?

**Comment by stipsan** [comment]
Yup! Resolved in [v4.6.0](https://github.com/stipsan/ioredis-mock/releases/tag/v4.6.0) 🎉
