### ISSUE TITLE
hmset should allow accepting an object

### ISSUE THREAD

**Issue by meltuhamy** [stipsan/ioredis-mock#322]
ioredis allows taking in an object as seen [here](https://github.com/luin/ioredis/blob/master/test/functional/transformer.js#L8-L13).

For some reason, this functionality is not supported with ioredis-mock. There even appears to be a [commented out test](https://github.com/stipsan/ioredis-mock/blob/7e68eba30b789f11bcc29375c35def4b60007376/test/commands/hmset.js#L14-L20) for that functionality...

To allow compatibility with the latest ioredis, I think ioredis-mock **should** allow hmset with object syntax.

**Comment by stipsan** [comment]
Hi,

I will work on it this week 🙂  Sorry for the long wait!

**Comment by DrMegavolt** [comment]
@stipsan  the way it works in `ioredis` is transformers. Do you plan to port those transformers?

**Comment by DrMegavolt** [comment]
@stipsan  Or another approach is to just embed https://github.com/luin/ioredis/blob/b216e4eb61d05ff639b162f23751acb111dde6e8/lib/command.js#L279-L289
into `hmset` command itself.

**Comment by stipsan** [comment]
@DrMegavolt yes the plan is to port them. I don't have time to implement them myself right now but if someone push a PR I'll make a new release 😄 

For now I'll just embed the command you linked me to, thanks for that btw! 🥇

**Comment by XVincentX** [comment]
The same goes for https://github.com/luin/ioredis/blob/b216e4eb61d05ff639b162f23751acb111dde6e8/lib/command.js#L291 as well.

**Comment by stipsan** [comment]
@XVincentX yep, I'll make a follow up issue about it shortly 🙂

**Comment by stipsan** [comment]
@XVincentX here it is https://github.com/stipsan/ioredis-mock/issues/339

@meltuhamy [v3.3.0](https://github.com/stipsan/ioredis-mock/releases/tag/v3.3.0) just got released with the fix for hmset 😉

**Comment by stipsan** [comment]
Thanks @XVincentX, I'll reopen this and take care of it tomorrow 😄

**Comment by DrMegavolt** [comment]
It is not an issue for Express-Gateway right now, I'm manually converting requests 
https://github.com/ExpressGateway/express-gateway/blob/80dd9b44b03e49a77f861844eb1579f5ea46a88e/lib/services/consumers/application.dao.js#L22

I believe that can be skipped in favor of request\reply transformers

**Comment by DrMegavolt** [comment]
And here it is  #342

**Comment by stipsan** [comment]
Closing this because it was implemented in [v3.3.0] using a stopgap, and will be replaced with the proper ioredis hmset argument transformer when #342 lands 🎉
