### ISSUE TITLE
Some commands fail when there's no data

### ISSUE THREAD

**Issue by XVincentX** [stipsan/ioredis-mock#328]
Hey!

I've been testing this module in order to speedup my unit tests and I'm having a strange behavior when I'm using the library with no data.

I have also created a small repl [on runkit](https://runkit.com/59ef79493b34ed00123dd9b0/59fc3a089a3eda0011473812)

Shouldn't the expected behaviour be to return undefined instead of throwing an exception?

**Comment by stipsan** [comment]
Hi! You're absolutely right and thanks for the report!

And thanks a ton for taking the time to make a runkit sample 😄 

I will focus on this project this week (I have been busy with https://github.com/stipsan/scroll-into-view-if-needed recently) as there's several bugs I want to fix, and there's still crucial features missing.

I can't make any promises but I'll work on a fix for this bug as fast as I can 🙂

**Comment by XVincentX** [comment]
That's great, and I'd be willing to help if needed.

Just to give you more context, we're in the process of replacing `node_redis` with `ioredis` for [Express Gateway](github.com/ExpressGateway/express-gateway), mainly for Sentinel support.

As we do provide a "memory" experience, that turned out to be really valuable for getting started, we really want to keep it.

I've been tracking what's missing here: https://github.com/ExpressGateway/express-gateway/pull/501

**Comment by stipsan** [comment]
That's awesome!

I'll be sure to give those issues priority, thanks for helping me triaging! 🥇👍 

Contributing an implementation is quite a bit of work, however a PR with a test case would be of great help as well when you find bugs or missing features.
It's hard to overstate how much time is saved if a test case for the bug/feature already exists in the system 😄

**Comment by XVincentX** [comment]
@stipsan I think we can close this, right?

**Comment by stipsan** [comment]
Yep 👍
