### ISSUE TITLE
Missing scan implementation

### ISSUE THREAD

**Issue by XVincentX** [stipsan/ioredis-mock#329]
This library is missing the `scan` implementation.
Is there any plan to add it?

**Comment by stipsan** [comment]
Yes, it's why I'm tracking which features are supported or not, here: https://github.com/stipsan/ioredis-mock/blob/master/compat.md

The goal is to reach 100% coverage so that ioredis-mock is a true drop-in replacement for ioredis 😄

**Comment by XVincentX** [comment]
Is there any plan to implement this command in the short term? As this is one of the last pieces missing to let us make the switch, we'd like to know whether we can help or you're already taming this part! Thanks again!

**Comment by DrMegavolt** [comment]
@stipsan  please check PR #334  it is implementation for that issue.

**Comment by stipsan** [comment]
> Is there any plan to implement this command in the short term?

I was going to answer `yes` here, but @DrMegavolt went ahead and did it already 😂 As soon as the new code got matching tests I'll merge and release 👍  I will circle back tomorrow and have enough time to help out on that.

**Comment by stipsan** [comment]
Just pushed v3.2.0 with this feature.
