### ISSUE TITLE
Implement support for argument and reply transformers

### ISSUE THREAD

**Issue by stipsan** [stipsan/ioredis-mock#339]
Replace stopgap solutions:
https://github.com/stipsan/ioredis-mock/blob/cffd1cfc03466442d7bb076dc1385b3af8852c46/src/commands/hmset.js#L9-L18
https://github.com/stipsan/ioredis-mock/blob/cffd1cfc03466442d7bb076dc1385b3af8852c46/src/command.js#L16-L17

with a proper `Command.setArgumentTransformer` and `Command.setReplyTransformer` interfaces.
As well as including the same default transformers found here:
https://github.com/luin/ioredis/blob/b216e4eb61d05ff639b162f23751acb111dde6e8/lib/command.js#L264-L277
https://github.com/luin/ioredis/blob/b216e4eb61d05ff639b162f23751acb111dde6e8/lib/command.js#L279-L289
https://github.com/luin/ioredis/blob/b216e4eb61d05ff639b162f23751acb111dde6e8/lib/command.js#L291-L300

The interface for defining them needs to be 100% compatible with this: 
https://github.com/luin/ioredis#transforming-arguments--replies

It looks like it means we need to implement it as singletons but this should be properly investigated. It's very important that the mock does not behave differently than the real ioredis on this.

**Comment by stipsan** [comment]
Notify this issue when there's progress: https://github.com/ExpressGateway/express-gateway/issues/537

**Comment by XVincentX** [comment]
I'll make sure to praise you in our next changelog. You've been extremely responsive!

**Comment by stipsan** [comment]
Just happy I can be of help :D and nice work on express-gateway, I think it’s going to have a positive impact on the expressjs community and help lower the barrier of entry for microservice architectures 👍😃

**Comment by XVincentX** [comment]
That's one of the goals, exactly!

**Comment by stipsan** [comment]
This was implemented in  #342 and released in https://github.com/stipsan/ioredis-mock/releases/tag/v3.4.0
