### ISSUE TITLE
*SCAN commands 

### ISSUE THREAD

**Issue by DrMegavolt** [stipsan/ioredis-mock#341]
I've implemented SCAN command based on this code 
https://github.com/hdachev/fakeredis/blob/master/lib/backend.js#L526-L589

HSCAN etc. are using the same helper function, the difference is mostly what keys are passed 
the task is mostly copy paste the SCAN implementation and write tests

**Comment by stipsan** [comment]
That's awesome! 🥇

**Comment by BastienAr** [comment]
Fixed in #393.
