### ISSUE TITLE
HSET is replacing HMSET and behave in the same way

### ISSUE THREAD

**Issue by DrMegavolt** [stipsan/ioredis-mock#345]
https://raw.githubusercontent.com/antirez/redis/4.0/00-RELEASENOTES
"HSET is now variadic, and HMSET is considered deprecated (but will be supported for years to come). Please use HSET in new code."

basically HSET can accept multiple key\values same as HMSET
HMSET myhash field1 "Hello" field2 "World" - OK
HSET myhash field1 "Hello" field2 "World" - Also OK

https://github.com/stipsan/ioredis-mock/blob/master/src/commands/hset.js#L1
still uses single key\value signature

**Comment by DrMegavolt** [comment]
the issue is super minor, but the fix may require introducing some `version` flag. because 2.8, 3.x are used widely

**Comment by stipsan** [comment]
Very interesting. I can imagine `ioredis` itself will want to solve this as well somehow, as the `hmset` reply transformer will make sense to have on `hset` for redis 4.0 users 😮

**Comment by DrMegavolt** [comment]
let's see what the response will be https://github.com/luin/ioredis/issues/551

**Comment by stipsan** [comment]
Agreed 👍

**Comment by mskuybeda** [comment]
I have fixed the HSET functionality for ioredis. I will work on this one now.

**Comment by stipsan** [comment]
Fixed in #1007
