### ISSUE TITLE
Processing args can't handle `null` or `undefined` values

### ISSUE THREAD

**Issue by joshhendo** [stipsan/ioredis-mock#352]
When doing a `set` command with a null value, like:
```
const potentialNull = null;
client.set('mykey', potentialNull, 'EX', '86400', 'NX')
```

An exception is thrown when attempting to convert the value to string at this line:
https://github.com/stipsan/ioredis-mock/blob/master/src/command.js#L10

Passing up a null value may be bad usage, however it seems to work fine with the real redis (with the value just being empty), so it would be good if the mocker could simulate this functionality.

**Comment by kkragenbrink** [comment]
I'm experiencing this myself, on `client.get`, as well.  This is actually a big problem, since `null` is the expected value of an unset key, and I want to be able to test for unset keys.
