### ISSUE TITLE
KEYS not consistent with redis - returns empty sets

### ISSUE THREAD

**Issue by josephg** [stipsan/ioredis-mock#357]
If you remove all items from a set in redis, the object shouldn't show up in the list of `KEYS` results. With ioredis-mock it does.

Test case:

```javascript
const Redis = require('ioredis')
const redis = new Redis()
redis.sadd('a', 'b')
redis.srem('a', 'b')
redis.keys('*', (err, data) => console.log(data))
```

With real redis (& ioredis):

```
$ node testcase.js 
[]
```

With `ioredis-mock`:

```
$ node testcase.js 
[ 'a' ]
```

**Comment by stipsan** [comment]
Thanks for the report, good find! 

If someone submits a PR with a fix I'll review and release promptly.
And if that doesn't happen before the weekend I'll look into it myself 😄
