### ISSUE TITLE
Use native promises instead of bluebird

### ISSUE THREAD

**Issue by ErinCall** [stipsan/ioredis-mock#560]
[Redis 4.0 has stopped using bluebird natively](https://github.com/luin/ioredis/blob/master/Changelog.md#400-2018-08-14). As a result, this code will work with ioredis-mock but fail with the real ioredis:

```JavaScript
return redisClient.hset(USERS_HASH_NAME, user.id, JSON.stringify(user))
  .thenReturn(user);
```

That was a confusing situation for me, as you can imagine!

ioredis 4 does offer support for bluebird promises, with a little setup:

```JavaScript
const Promise = require('bluebird');
const Redis = require('ioredis');

Redis.Promise = Promise;
```

**Comment by stipsan** [comment]
Indeed that must've been confusing!

PRs are welcome on this 😄 There's a lot of code that can be deleted once we follow in Redis 4.0's footsteps and drop support for node versions older than v4. In addition to promises, [node v4 and later](https://node.green) supports `Set`, `Map`, `Object.keys` and more that we're currently polyfilling 🤔
