### ISSUE TITLE
zscanStream behavior doesn't match ioredis

### ISSUE THREAD

**Issue by philraj** [stipsan/ioredis-mock#602]
When using zscanStream from ioredis-mock, the replies sent back by the mocked redis incorrectly exclude the scores of the sorted set members.

Example runkit:
https://runkit.com/philraj/5b634fbf878b10001129a951

If you try this with an actual instance of Redis and ioredis, you'll see that zscanStream is supposed to send back an array containing the score and the member (so in reality if you want just the members, you have to iterate over every 2nd index).

**Comment by stipsan** [comment]
Thanks for the report and the attached run kit 🙂 I’m in the middle of starting in a new job as well as moving out of my flat to a new place so I don’t know when I’ll have time to work on a fix. But PRs are welcome and pushing out a new version does not require my laptop (my phone will do!) so I can do that fairly quick 😃
