### ISSUE TITLE
hdel throws an error if key does not exist

### ISSUE THREAD

**Issue by KashiMoonactive** [stipsan/ioredis-mock#622]
Hi,
Please see PR: https://github.com/stipsan/ioredis-mock/pull/624
I have committed a fix for this issue.

If key does not exist the redis mock throws an error, and as the redis documentation states, it should return 0

**Comment by stipsan** [comment]
Fixed in [v4.3.1](https://www.npmjs.com/package/ioredis-mock/v/4.3.1)
