### ISSUE TITLE
Update ioredis-mock to support zcard

### ISSUE THREAD

**Issue by jkasiraj** [stipsan/ioredis-mock#702]
I want to use ioredis-mock with a third party library that makes use of zcard.

I don't have a great understanding of ioredis, but just glancing at the code I don't think it would be too hard to add support for zcard? Maybe something like this:

```
import Map from 'es6-map';

export function zcard(key) {
  const map = this.data.get(key);
  if (!map) {
    return 0;
  }

  if (this.data.has(key) && !(this.data.get(key) instanceof Map)) {
    return 0;
  }

  return this.data.get(key).size;
}
```

**Comment by stipsan** [comment]
PRs welcome 🙂

**Comment by ljht** [comment]
PR opened at https://github.com/stipsan/ioredis-mock/pull/732
