### ISSUE TITLE
Pub/sub setup not consistent with ioredis

### ISSUE THREAD

**Issue by nmargaritis** [stipsan/ioredis-mock#773]
It appears that the functionality of redis pubsub differs from how ioredis and similar libraries are meant to be setup.

### Expected Behavior
By executing the following code I would expect the subscriber be able to listen to the published messages.
```
var Redis = require('ioredis-mock');
var redisPubSub = new Redis();
var redisSync = new Redis();
redisPubSub.on('message', (channel, message) => {
    console.log(message);
});
redisPubSub.subscribe('emails');
redisSync.publish('emails', 'admin@example.com');
```
Nothing gets printed, as if the client is not initiated from the `redisPubSub` with the `createConnectedClient` method, publisher is not able to reach the subscriber.

**Similar Code from ioredis**
```
var Redis = require('ioredis');
var sub = new Redis();
var publisher = new Redis();
sub.on('message', (channel, message) => {
    console.log(message);
});
sub.subscribe('emails');
publisher.publish('emails', 'admin@example.com');
```
Requires a redis server running, console log prints as expected.

### Actual Behavior

```
var Redis = require('ioredis-mock');
var redisPubSub = new Redis();
var redisSync = redisPubSub.createConnectedClient();
redisPubSub.on('message', (channel, message) => {
    console.log(message);
});
redisPubSub.subscribe('emails');
redisSync.publish('emails', 'admin@example.com');
```
Message prints out.

### Why this is problematic

Assuming that this project is used to mock redis while testing an application that creates multiple redis clients with the convention of `ioredis`/`node-redis` (new Redis())

This makes your implementation of pub/sub not a plug and play solution.

**The use case that your implementation is not supporting is that,  if the subscribers are created within the codebase (so no room to link them up with the publisher), and the publishers are created within the tests, these 2 are not able to communicate...**

Such use case, is mostly what a tester will look to simulate.

Similar libraries support such behavior, like https://github.com/yeahoffline/redis-mock in which new Redis instances are able to reach one another via the pubsub, and there is no need to link them up the way this library does.

**Comment by stipsan** [comment]
Hey and thanks for your detailed report 😄 

This functionality is indeed missing, and I agree with you that it should "just work", like redis-mock. The ultimate goal is for this library to be truly a drop-in replacement.

PRs are welcome 👍

**Comment by sibelius** [comment]
is there a workaround for this?

**Comment by sibelius** [comment]
should we share the same `channels` for the same IORedis options?

when should we not share this?

```jsx
createConnectedClient(options = {}) {
    const mock = new RedisMock(options);
    mock.expires =
      typeof options.keyPrefix === 'string'
        ? this.expires.withKeyPrefix(options.keyPrefix)
        : this.expires;
    mock.data =
      typeof options.keyPrefix === 'string'
        ? this.data.withKeyPrefix(options.keyPrefix)
        : this.data;
    mock.channels = this.channels;
    mock.patternChannels = this.patternChannels;
    return mock;
  }
```

**Comment by stipsan** [comment]
@sibelius yes we should, and PRs for that functionality is welcome 🙂

**Comment by sibelius** [comment]
for now I've solved this on the jest mock level like this:

```jsx
jest.mock('ioredis', () => {
  const Redis = require('ioredis-mock');

  if (typeof Redis === 'object') {
    // the first mock is an ioredis shim because ioredis-mock depends on it
    // https://github.com/stipsan/ioredis-mock/blob/master/src/index.js#L101-L111
    return {
      Command: { _transformer: { argument: {}, reply: {} } },
    };
  }

  let instance = null;

  // second mock for our code
  return function (...args) {
    if (instance) {
      return instance.createConnectedClient();
    }

    instance = new Redis(args);

    return instance;
  };
});
```

it will create 1 RedisMock for the first new call, and then it is gonna use createConnectedClient for the other calls

**Comment by stipsan** [comment]
Historically they've not been shared, and required the `createConnectedClient` opt-in, as it was the simplest way to implement it.

The right way to implement it would be to reuse the same `expires`, `data`, `channels`, and `patternChannels` properties for matching connection options. This would bring us much closer to real-world behavior.

In other words it would be super useful if ioredis-mock could do this:
```js
const redis1 = new Redis();
const redis2 = new Redis(6379);
const redis3 = new Redis('127.0.0.1');
const redis4 = new Redis({ port: 6379, host: '127.0.0.1' });
// Different port, which signals a diff server and shouldn't share props with the others
const redis5 = new Redis(6380);

await redis.set('foo', 'bar');

await Promise.all([
  redis1.get('foo'),
  redis2.get('foo'),
  redis3.get('foo'),
  redis4.get('foo'),
  redis5.get('foo'),
]); // ["bar", "bar", "bar", "bar", undefined]
```

Then we could finally deprecate `createConnectedClient` 😄  I don't have time to work on this myself anytime soon, I can only look at PRs coming in :/

**Comment by sibelius** [comment]
One of the "problems" of the current code is that each command uses `this` directly to consume data and channels

We probably need a Map or WeakMap to store this data per connections options

but we would need to change to `this.getData()` `this.getChannel()`, instead of this.channel

do you have some suggestions to improve this?

**Comment by stipsan** [comment]
Yep it needs a rethink.
I'd prefer setters and getters instead of calling `this.getData()` in the commands.
The way things are mutating `this.data` in the various commands are also a problem. Right now we're somewhat "protected" against race conditions since each instance of the client has its own `data`, `channel` etc. Changing it to only be isolated if the server connection don't match we're far more susceptible to said race conditions.
To avoid them I'd like to run `JSON.parse(JSON.stringify())` whenever the data is fetched, to ensure that between the getter and the setter things can't unexpectedly mutate.

As for the Map that handles each "instance" based on connection options we could serialize the options to the redis format URL: https://github.com/luin/ioredis#connect-to-redis

**Comment by nmargaritis** [comment]
> is there a workaround for this?

What I ended up doing, was to bring a normal redis instance in the test environment with docker and use `ioredis` directly in our tests suite that is now run through docker.

This is something that we could do cause it was already supported in our integration with the CI (Jenkins) so the tests could run as expected in the CI. If you plan to execute your tests in the CI, you have to consider that you might need to do changes there.

If you find this a helpful workaround, you could try it. However, fixing the issue in this project, will allow the whole concept to be done in a plug and play fashion without the need of docker.

**Comment by stipsan** [comment]
@nmargaritis actually it would be amazing if we had that setup running here. We could run the same tests in both environments and use the `ioredis` with `redis` on docker to verify that the mock is behaving in the same way 😄

**Comment by sibelius** [comment]
if someone wanna continue my pull request https://github.com/stipsan/ioredis-mock/pull/997 feel free

**Comment by nmargaritis** [comment]
> @nmargaritis actually it would be amazing if we had that setup running here. We could run the same tests in both environments and use the `ioredis` with `redis` on docker to verify that the mock is behaving in the same way 😄

Unfortunately, I do not have a plug and play test example. But if I get some free time, i will try to review old commits and build a small test that can replicate the issue.
