### ISSUE TITLE
info() not implemented

### ISSUE THREAD

**Issue by panjan** [stipsan/ioredis-mock#841]
Hello, 

I tried passing `ioredis-mock` to the ioredis-based queue package [`bull`](https://github.com/OptimalBits/bull) and got the following error.

```
    TypeError: client.info is not a function
      at getRedisVersion (node_modules/bull/lib/queue.js:1187:17)
      at new Queue (node_modules/bull/lib/queue.js:183:5)
      at Object.Queue [as default] (node_modules/bull/lib/queue.js:89:12)
      at new Orchestrator (src/orchestrator/orchestrator.ts:1769:34)
      at Object.<anonymous> (src/server/route/__tests__/flight.test.ts:35:24)
```

The same works with regular `ioredis`. I was able to work around this issue by [implementing the missing method in my fork](https://github.com/panjan/ioredis-mock/commit/34e618e8139b3e6f15cefe1df1ffd3bb5cf63869).

[Here's](https://github.com/OptimalBits/bull/blob/develop/lib/queue.js#L1220) the `info()` function called from `bull`.

What are the plans regarding the `info()` function? I'll be happy to submit a PR if you want to make it into a feature.

**Comment by stipsan** [comment]
Hi! 

It's one of the commands we want to support. You can see the full list and their status here: https://github.com/stipsan/ioredis-mock/blob/master/compat.md

You're more than welcome to submit a PR with your fork's implementation 😄 🎉
