### ISSUE TITLE
zinterstore feature request

### ISSUE THREAD

**Issue by fdussert** [stipsan/ioredis-mock#862]
Hi,
Your lib is just awesome, thanks for all.
Do you plan to implement the zinterstore command ?
I really need this one for my tests :/

**Comment by mishan** [comment]
@fdussert I have a work in progress PR to add `ZINTERSTORE` -- just need to make sure all edge cases are handled

Note: AGGREGATE and WEIGHT options are not currently supported.

**Comment by mishan** [comment]
https://github.com/stipsan/ioredis-mock/pull/863

**Comment by fdussert** [comment]
Awesome, thank you
