### ISSUE TITLE
zrangebyscore does not support LIMIT

### ISSUE THREAD

**Issue by mishan** [stipsan/ioredis-mock#918]
zrangebyscore does not support LIMIT offset count

**Comment by barakharizima** [comment]
Any news about this one?

**Comment by mishan** [comment]
@barakharizima See PR #919 . Just waiting for @stipsan to acknowledge it. He's probably too busy right now.

**Comment by barakharizima** [comment]
@mishan great to see a PR is already in place, but I actually need it for another command `zrevrangebyscore` 😅
I think all range commands which support LIMIT option will probably need it too, so maybe it's worth adding it to the PR, what do you think?

**Comment by mishan** [comment]
@barakharizima Yeah, that's reasonable. I'll find some time soon and add it. I already had the sense to make some of this code reusable
