### ISSUE TITLE
hscan returns only fields

### ISSUE THREAD

**Issue by nkzawa** [stipsan/ioredis-mock#962]
It should return array field and value, for every returned element of the Hash.

```sh
hset key field1 1
hset key field2 2
```

```js
// ioredis
redis.hscan('key', 0).then(console.log); // [ '0', [ 'field1', '1', 'field2', '2' ] ]

// ioredis-mock
redisMock.hscan('key', 0).then(console.log); // [ '0', [ 'field1', 'field2' ] ]
```

This problem happens with `hscanStream` as well

**Comment by elad-sf** [comment]
had it too, you can monkey patch it..
`before(() => {
    const originalHscan = redisMock.hscan;
    redisMock.hscan = async (key, ...args) => {
        const [cursor, results] = await originalHscan(key, ...args);
        const trueResults = [];
        for (let i = 0, j = 0; i < results.length; i++, j += 2) {
            trueResults[j] = results[i];
            trueResults[j + 1] = await redisMock.hget(key, results[i]);
        }

        return [cursor, trueResults];
    };
});`

**Comment by silverwind** [comment]
Another variation of the monkey patch:

```js
redis.hscan = async (hash, ...args) => {
  const [cursor, keys] = await origHscan(hash, ...args);
  const ret = [];
  for (const key of keys) {
    ret.push(key, await redis.hget(hash, key));
  }
  return [cursor, ret];
}
```
